---
title: "Test of boxed text"
output:
  html_document:
    df_print: paged
  pdf_document: null
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<style>
div.blue { background-color:#e6f0ff; border-radius: 5px; padding: 20px;}
</style>

<div class = "blue">
I recommend that you check out the properties of the of the Poisson distribution a bit by simulating data with the `rpois` function with different values of `lambda` (try both small and large values). Plot histograms and compute means and variances. 
</div>

But this only works for html...

---

I recommend that you check out the properties of the of the Poisson distribution a bit by simulating data with the `rpois` function with different values of `lambda` (try both small and large values). Plot histograms and compute means and variances. 

>> Test

---

---

<div class = "blue">
> I recommend that you check out the properties of the of the Poisson distribution a bit by simulating data with the `rpois` function with different values of `lambda` (try both small and large values). Plot histograms and compute means and variances. 
</div>

---

Does ths same thing

***
I recommend that you check out the properties of the of the Poisson distribution a bit by simulating data with the `rpois` function with different values of `lambda` (try both small and large values). Plot histograms and compute means and variances. 

***

>I recommend that you check out the properties of the of the Poisson distribution a bit by simulating data with the `rpois` function with different values of `lambda` (try both small and large values). Plot histograms and compute means and variances. 
